"""inicio

Revision ID: 09adfc5fd0ac
Revises: 
Create Date: 2025-08-21 17:35:24.089541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09adfc5fd0ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_atividade_estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_atividade_estabelecimento_id'), 'aux_atividade_estabelecimento', ['id'], unique=False)
    op.create_table('aux_carater_internacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_carater_internacao_id'), 'aux_carater_internacao', ['id'], unique=False)
    op.create_table('aux_classificacao_estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_classificacao_estabelecimento_id'), 'aux_classificacao_estabelecimento', ['id'], unique=False)
    op.create_table('aux_faixa_etaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_faixa_etaria_id'), 'aux_faixa_etaria', ['id'], unique=False)
    op.create_table('aux_gravidez_risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_gravidez_risco_id'), 'aux_gravidez_risco', ['id'], unique=False)
    op.create_table('aux_identificacao_aih',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_identificacao_aih_id'), 'aux_identificacao_aih', ['id'], unique=False)
    op.create_table('aux_modalidade_internacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_modalidade_internacao_id'), 'aux_modalidade_internacao', ['id'], unique=False)
    op.create_table('aux_motivo_saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_motivo_saida_id'), 'aux_motivo_saida', ['id'], unique=False)
    op.create_table('aux_origem_informacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_origem_informacoes_id'), 'aux_origem_informacoes', ['id'], unique=False)
    op.create_table('aux_raca_cor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_raca_cor_id'), 'aux_raca_cor', ['id'], unique=False)
    op.create_table('aux_sus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_sus_id'), 'aux_sus', ['id'], unique=False)
    op.create_table('aux_tempo_gestacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_tempo_gestacao_id'), 'aux_tempo_gestacao', ['id'], unique=False)
    op.create_table('aux_tipo_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_tipo_equipamento_id'), 'aux_tipo_equipamento', ['id'], unique=False)
    op.create_table('aux_tipo_financiamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_tipo_financiamento_id'), 'aux_tipo_financiamento', ['id'], unique=False)
    op.create_table('aux_tipo_parto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_tipo_parto_id'), 'aux_tipo_parto', ['id'], unique=False)
    op.create_table('aux_tipo_vacina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_tipo_vacina_id'), 'aux_tipo_vacina', ['id'], unique=False)
    op.create_table('aux_tipos_leito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_tipos_leito_id'), 'aux_tipos_leito', ['id'], unique=False)
    op.create_table('aux_vinculo_profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aux_vinculo_profissional_id'), 'aux_vinculo_profissional', ['id'], unique=False)
    op.create_table('localAcesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.BigInteger(), nullable=True),
    sa.Column('Logradouro', sa.String(), nullable=True),
    sa.Column('Numero', sa.String(), nullable=True),
    sa.Column('Bairro', sa.String(), nullable=True),
    sa.Column('CEP', sa.BigInteger(), nullable=True),
    sa.Column('Cidade', sa.String(), nullable=True),
    sa.Column('Estado', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.BigInteger(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localAcesso_id'), 'localAcesso', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('localacesso_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['localacesso_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acesso_id'), 'acesso', ['id'], unique=False)
    op.create_table('autorizacao_internacao_hospitalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('NumeroAIH', sa.Integer(), nullable=True),
    sa.Column('Identificacao', sa.Integer(), nullable=True),
    sa.Column('EspecialidadeLeito', sa.Integer(), nullable=True),
    sa.Column('ModalidadeInternacao', sa.Integer(), nullable=True),
    sa.Column('AIHAnterior', sa.Integer(), nullable=True),
    sa.Column('DataEmissao', sa.Date(), nullable=True),
    sa.Column('DataInternacao', sa.Date(), nullable=True),
    sa.Column('DataSaida', sa.Date(), nullable=True),
    sa.Column('ProcedimentoSolicitado', sa.Integer(), nullable=True),
    sa.Column('CaraterInternacao', sa.Integer(), nullable=True),
    sa.Column('MotivoSaida', sa.Integer(), nullable=True),
    sa.Column('CNSSolicitante', sa.Integer(), nullable=True),
    sa.Column('CNSResponsavel', sa.Integer(), nullable=True),
    sa.Column('CNSAutorizador', sa.Integer(), nullable=True),
    sa.Column('DiagnosticoPrincipal', sa.String(length=4), nullable=True),
    sa.Column('CNSPaciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CaraterInternacao'], ['aux_carater_internacao.id'], ),
    sa.ForeignKeyConstraint(['EspecialidadeLeito'], ['aux_tipos_leito.id'], ),
    sa.ForeignKeyConstraint(['Identificacao'], ['aux_identificacao_aih.id'], ),
    sa.ForeignKeyConstraint(['ModalidadeInternacao'], ['aux_modalidade_internacao.id'], ),
    sa.ForeignKeyConstraint(['MotivoSaida'], ['aux_motivo_saida.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autorizacao_internacao_hospitalar_id'), 'autorizacao_internacao_hospitalar', ['id'], unique=False)
    op.create_table('autorizacao_procedimento_ambulatorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('CPFAutorizador', sa.Integer(), nullable=True),
    sa.Column('Ocupacao', sa.Integer(), nullable=True),
    sa.Column('CNS', sa.Integer(), nullable=True),
    sa.Column('Data', sa.Date(), nullable=True),
    sa.Column('Procedimento', sa.Integer(), nullable=True),
    sa.Column('CID10Principal', sa.String(length=4), nullable=True),
    sa.Column('CID10Secundario', sa.String(length=4), nullable=True),
    sa.Column('CID10CausasAssociadas', sa.String(length=4), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=True),
    sa.Column('Origem', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['Origem'], ['aux_origem_informacoes.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autorizacao_procedimento_ambulatorial_id'), 'autorizacao_procedimento_ambulatorial', ['id'], unique=False)
    op.create_table('cobertura_vacinal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('FaixaEtaria', sa.Integer(), nullable=True),
    sa.Column('Vacina', sa.Integer(), nullable=True),
    sa.Column('QuantidadeMasculino', sa.Integer(), nullable=True),
    sa.Column('QuantidadeFeminino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FaixaEtaria'], ['aux_faixa_etaria.id'], ),
    sa.ForeignKeyConstraint(['Vacina'], ['aux_tipo_vacina.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobertura_vacinal_id'), 'cobertura_vacinal', ['id'], unique=False)
    op.create_table('estabelecimento_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('Codigo', sa.Integer(), nullable=True),
    sa.Column('Tipo', sa.Integer(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=True),
    sa.Column('QuantidadeSUS', sa.Integer(), nullable=True),
    sa.Column('DisponibilidadeSUS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DisponibilidadeSUS'], ['aux_sus.id'], ),
    sa.ForeignKeyConstraint(['Tipo'], ['aux_tipo_equipamento.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimento_equipamento_id'), 'estabelecimento_equipamento', ['id'], unique=False)
    op.create_table('estabelecimento_leito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('TipoLeito', sa.Integer(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=True),
    sa.Column('QuantidadeSUS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TipoLeito'], ['aux_tipos_leito.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimento_leito_id'), 'estabelecimento_leito', ['id'], unique=False)
    op.create_table('estabelecimento_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('CNPJ', sa.Integer(), nullable=True),
    sa.Column('NomeFantasia', sa.String(length=255), nullable=True),
    sa.Column('RazaoSocial', sa.String(length=255), nullable=True),
    sa.Column('Endereco', sa.String(length=255), nullable=True),
    sa.Column('Cidade', sa.String(length=255), nullable=False),
    sa.Column('Estado', sa.String(length=2), nullable=False),
    sa.Column('Logradouro', sa.String(length=255), nullable=False),
    sa.Column('Numero', sa.String(length=10), nullable=False),
    sa.Column('Bairro', sa.String(length=255), nullable=False),
    sa.Column('CEP', sa.Integer(), nullable=True),
    sa.Column('CPFDiretor', sa.String(length=11), nullable=True),
    sa.Column('Tipo', sa.Integer(), nullable=True),
    sa.Column('AtividadePrincipal', sa.Integer(), nullable=True),
    sa.Column('AtividadeSecundaria', sa.Integer(), nullable=True),
    sa.Column('SistemaSUS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AtividadePrincipal'], ['aux_atividade_estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['AtividadeSecundaria'], ['aux_atividade_estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['SistemaSUS'], ['aux_sus.id'], ),
    sa.ForeignKeyConstraint(['Tipo'], ['aux_classificacao_estabelecimento.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimento_saude_id'), 'estabelecimento_saude', ['id'], unique=False)
    op.create_table('ficha_programacao_orcamentaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('Procedimento', sa.Integer(), nullable=True),
    sa.Column('Financiamento', sa.Integer(), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=True),
    sa.Column('ValorUnitario', sa.Float(), nullable=True),
    sa.Column('ValorTotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['Financiamento'], ['aux_tipo_financiamento.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ficha_programacao_orcamentaria_id'), 'ficha_programacao_orcamentaria', ['id'], unique=False)
    op.create_table('mae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CPF', sa.Integer(), nullable=True),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.Column('DataNascimento', sa.Date(), nullable=True),
    sa.Column('Raca', sa.Integer(), nullable=True),
    sa.Column('QuantidadeConsulta', sa.Integer(), nullable=True),
    sa.Column('GravidezRisco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GravidezRisco'], ['aux_gravidez_risco.id'], ),
    sa.ForeignKeyConstraint(['Raca'], ['aux_raca_cor.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mae_id'), 'mae', ['id'], unique=False)
    op.create_table('morbidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('FaixaEtaria', sa.Integer(), nullable=True),
    sa.Column('CategoriaCID', sa.String(length=6), nullable=True),
    sa.Column('SubCategoriaCID', sa.String(length=6), nullable=True),
    sa.Column('QuantidadeMasculino', sa.Integer(), nullable=True),
    sa.Column('QuantidadeFeminino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FaixaEtaria'], ['aux_faixa_etaria.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_morbidade_id'), 'morbidade', ['id'], unique=False)
    op.create_table('mortalidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('FaixaEtaria', sa.Integer(), nullable=True),
    sa.Column('CategoriaCID', sa.String(length=6), nullable=True),
    sa.Column('SubCategoriaCID', sa.String(length=6), nullable=True),
    sa.Column('QuantidadeMasculino', sa.Integer(), nullable=True),
    sa.Column('QuantidadeFeminino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FaixaEtaria'], ['aux_faixa_etaria.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mortalidade_id'), 'mortalidade', ['id'], unique=False)
    op.create_table('nascido_vivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CPFMae', sa.Integer(), nullable=True),
    sa.Column('NumeroDNV', sa.Integer(), nullable=True),
    sa.Column('Raca', sa.Integer(), nullable=True),
    sa.Column('DataNascimento', sa.Date(), nullable=True),
    sa.Column('TipoParto', sa.Integer(), nullable=True),
    sa.Column('TempoGestacao', sa.Integer(), nullable=True),
    sa.Column('PesoNascimento', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['Raca'], ['aux_raca_cor.id'], ),
    sa.ForeignKeyConstraint(['TempoGestacao'], ['aux_tempo_gestacao.id'], ),
    sa.ForeignKeyConstraint(['TipoParto'], ['aux_tipo_parto.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nascido_vivo_id'), 'nascido_vivo', ['id'], unique=False)
    op.create_table('saude_mental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('FaixaEtaria', sa.Integer(), nullable=True),
    sa.Column('CategoriaCID', sa.String(length=6), nullable=True),
    sa.Column('SubCategoriaCID', sa.String(length=6), nullable=True),
    sa.Column('QuantidadeMasculino', sa.Integer(), nullable=True),
    sa.Column('QuantidadeFeminino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FaixaEtaria'], ['aux_faixa_etaria.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saude_mental_id'), 'saude_mental', ['id'], unique=False)
    op.create_table('solicitacao_procedimento_ambulatorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('Data', sa.Date(), nullable=True),
    sa.Column('Procedimento', sa.Integer(), nullable=True),
    sa.Column('CID10Principal', sa.String(length=4), nullable=True),
    sa.Column('CID10Secundario', sa.String(length=4), nullable=True),
    sa.Column('CID10CausasAssociadas', sa.String(length=4), nullable=True),
    sa.Column('Quantidade', sa.Integer(), nullable=True),
    sa.Column('Origem', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['Origem'], ['aux_origem_informacoes.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacao_procedimento_ambulatorial_id'), 'solicitacao_procedimento_ambulatorial', ['id'], unique=False)
    op.create_table('unidade_gestora',
    sa.Column('identificador', sa.Integer(), nullable=False),
    sa.Column('unidade_gestora', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('codigo_ua', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.PrimaryKeyConstraint('identificador'),
    sa.UniqueConstraint('codigo_ua'),
    sa.UniqueConstraint('identificador'),
    sa.UniqueConstraint('unidade_gestora')
    )
    op.create_table('vinculo_profissional_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_alteracao', sa.Date(), nullable=True),
    sa.Column('CNES', sa.Integer(), nullable=True),
    sa.Column('CPF', sa.Integer(), nullable=True),
    sa.Column('Matricula', sa.Integer(), nullable=True),
    sa.Column('Vinculo', sa.Integer(), nullable=True),
    sa.Column('Ocupacao', sa.Integer(), nullable=True),
    sa.Column('CargaHorariaAmbulatorio', sa.Integer(), nullable=True),
    sa.Column('CargaHorariaTotal', sa.Integer(), nullable=True),
    sa.Column('DataInicioVinculo', sa.Date(), nullable=True),
    sa.Column('DataFimVinculo', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Vinculo'], ['aux_vinculo_profissional.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['localAcesso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinculo_profissional_saude_id'), 'vinculo_profissional_saude', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vinculo_profissional_saude_id'), table_name='vinculo_profissional_saude')
    op.drop_table('vinculo_profissional_saude')
    op.drop_table('unidade_gestora')
    op.drop_index(op.f('ix_solicitacao_procedimento_ambulatorial_id'), table_name='solicitacao_procedimento_ambulatorial')
    op.drop_table('solicitacao_procedimento_ambulatorial')
    op.drop_index(op.f('ix_saude_mental_id'), table_name='saude_mental')
    op.drop_table('saude_mental')
    op.drop_index(op.f('ix_nascido_vivo_id'), table_name='nascido_vivo')
    op.drop_table('nascido_vivo')
    op.drop_index(op.f('ix_mortalidade_id'), table_name='mortalidade')
    op.drop_table('mortalidade')
    op.drop_index(op.f('ix_morbidade_id'), table_name='morbidade')
    op.drop_table('morbidade')
    op.drop_index(op.f('ix_mae_id'), table_name='mae')
    op.drop_table('mae')
    op.drop_index(op.f('ix_ficha_programacao_orcamentaria_id'), table_name='ficha_programacao_orcamentaria')
    op.drop_table('ficha_programacao_orcamentaria')
    op.drop_index(op.f('ix_estabelecimento_saude_id'), table_name='estabelecimento_saude')
    op.drop_table('estabelecimento_saude')
    op.drop_index(op.f('ix_estabelecimento_leito_id'), table_name='estabelecimento_leito')
    op.drop_table('estabelecimento_leito')
    op.drop_index(op.f('ix_estabelecimento_equipamento_id'), table_name='estabelecimento_equipamento')
    op.drop_table('estabelecimento_equipamento')
    op.drop_index(op.f('ix_cobertura_vacinal_id'), table_name='cobertura_vacinal')
    op.drop_table('cobertura_vacinal')
    op.drop_index(op.f('ix_autorizacao_procedimento_ambulatorial_id'), table_name='autorizacao_procedimento_ambulatorial')
    op.drop_table('autorizacao_procedimento_ambulatorial')
    op.drop_index(op.f('ix_autorizacao_internacao_hospitalar_id'), table_name='autorizacao_internacao_hospitalar')
    op.drop_table('autorizacao_internacao_hospitalar')
    op.drop_index(op.f('ix_acesso_id'), table_name='acesso')
    op.drop_table('acesso')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_localAcesso_id'), table_name='localAcesso')
    op.drop_table('localAcesso')
    op.drop_index(op.f('ix_aux_vinculo_profissional_id'), table_name='aux_vinculo_profissional')
    op.drop_table('aux_vinculo_profissional')
    op.drop_index(op.f('ix_aux_tipos_leito_id'), table_name='aux_tipos_leito')
    op.drop_table('aux_tipos_leito')
    op.drop_index(op.f('ix_aux_tipo_vacina_id'), table_name='aux_tipo_vacina')
    op.drop_table('aux_tipo_vacina')
    op.drop_index(op.f('ix_aux_tipo_parto_id'), table_name='aux_tipo_parto')
    op.drop_table('aux_tipo_parto')
    op.drop_index(op.f('ix_aux_tipo_financiamento_id'), table_name='aux_tipo_financiamento')
    op.drop_table('aux_tipo_financiamento')
    op.drop_index(op.f('ix_aux_tipo_equipamento_id'), table_name='aux_tipo_equipamento')
    op.drop_table('aux_tipo_equipamento')
    op.drop_index(op.f('ix_aux_tempo_gestacao_id'), table_name='aux_tempo_gestacao')
    op.drop_table('aux_tempo_gestacao')
    op.drop_index(op.f('ix_aux_sus_id'), table_name='aux_sus')
    op.drop_table('aux_sus')
    op.drop_index(op.f('ix_aux_raca_cor_id'), table_name='aux_raca_cor')
    op.drop_table('aux_raca_cor')
    op.drop_index(op.f('ix_aux_origem_informacoes_id'), table_name='aux_origem_informacoes')
    op.drop_table('aux_origem_informacoes')
    op.drop_index(op.f('ix_aux_motivo_saida_id'), table_name='aux_motivo_saida')
    op.drop_table('aux_motivo_saida')
    op.drop_index(op.f('ix_aux_modalidade_internacao_id'), table_name='aux_modalidade_internacao')
    op.drop_table('aux_modalidade_internacao')
    op.drop_index(op.f('ix_aux_identificacao_aih_id'), table_name='aux_identificacao_aih')
    op.drop_table('aux_identificacao_aih')
    op.drop_index(op.f('ix_aux_gravidez_risco_id'), table_name='aux_gravidez_risco')
    op.drop_table('aux_gravidez_risco')
    op.drop_index(op.f('ix_aux_faixa_etaria_id'), table_name='aux_faixa_etaria')
    op.drop_table('aux_faixa_etaria')
    op.drop_index(op.f('ix_aux_classificacao_estabelecimento_id'), table_name='aux_classificacao_estabelecimento')
    op.drop_table('aux_classificacao_estabelecimento')
    op.drop_index(op.f('ix_aux_carater_internacao_id'), table_name='aux_carater_internacao')
    op.drop_table('aux_carater_internacao')
    op.drop_index(op.f('ix_aux_atividade_estabelecimento_id'), table_name='aux_atividade_estabelecimento')
    op.drop_table('aux_atividade_estabelecimento')
    # ### end Alembic commands ###
