"""typos

Revision ID: b3a9cbd7ca5e
Revises: bd32f99bcc8b
Create Date: 2025-09-04 11:51:02.214662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a9cbd7ca5e'
down_revision: Union[str, None] = 'bd32f99bcc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSSolicitante',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSResponsavel',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSAutorizador',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSPaciente',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('autorizacao_procedimento_ambulatorial', 'CPFAutorizador',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('estabelecimento_saude', 'CNPJ',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('estabelecimento_saude', 'CEP',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('mae', 'CPF',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('nascido_vivo', 'CPFMae',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'unidade_gestora', ['identificador'])
    op.alter_column('vinculo_profissional_saude', 'CPF',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vinculo_profissional_saude', 'CPF',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'unidade_gestora', type_='unique')
    op.alter_column('nascido_vivo', 'CPFMae',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('mae', 'CPF',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('estabelecimento_saude', 'CEP',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('estabelecimento_saude', 'CNPJ',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('autorizacao_procedimento_ambulatorial', 'CPFAutorizador',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSPaciente',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSAutorizador',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSResponsavel',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('autorizacao_internacao_hospitalar', 'CNSSolicitante',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
